[pytest]
DJANGO_SETTINGS_MODULE = Django_star.settings
python_files = test_*.py *_test.py
testpaths = apps tests

# Добавь эту строку для поиска модулей
pythonpath = . src apps

norecursedirs = .env .venv venv env node_modules migrations
addopts = -v --strict-markers