[pytest]
DJANGO_SETTINGS_MODULE = Django_star.settings
python_files = test_*.py *_test.py
testpaths = apps tests

# Добавляем пути для поиска модулей
pythonpath = src apps

# Добавьте эти настройки
norecursedirs = .env .venv venv env node_modules migrations
addopts = -v --strict-markers