"""
Django settings for Django_star project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# src/Django_star/settings.py
from pathlib import Path
import sys

from .config import settings  # ← импортируем из config.py

# BASE_DIR - корень проекта (где manage.py)
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Добавляем apps в PYTHONPATH для импортов
APPS_DIR = BASE_DIR / 'apps'
if APPS_DIR.exists() and str(APPS_DIR) not in sys.path:
    sys.path.insert(0, str(APPS_DIR))

# ============================================
# БЕЗОПАСНОСТЬ
# ============================================
SECRET_KEY = settings.SECRET_KEY
DEBUG = settings.DEBUG
ALLOWED_HOSTS = settings.ALLOWED_HOSTS

# ============================================
# ПРИЛОЖЕНИЯ
# ============================================
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

LOCAL_APPS = [
    'my_app',  # без apps. префикса, так как apps в PYTHONPATH
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS

# ============================================
# MIDDLEWARE
# ============================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================
# URL И WSGI
# ============================================
ROOT_URLCONF = 'Django_star.urls'
WSGI_APPLICATION = 'Django_star.wsgi.application'

# ============================================
# ШАБЛОНЫ
# ============================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ============================================
# БАЗА ДАННЫХ
# ============================================
if settings.USE_POSTGRES:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': settings.DB_NAME,
            'USER': settings.DB_USER,
            'PASSWORD': settings.DB_PASSWORD,
            'HOST': settings.DB_HOST,
            'PORT': settings.DB_PORT,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }

# ============================================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# ============================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================
# ИНТЕРНАЦИОНАЛИЗАЦИЯ
# ============================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================================
# СТАТИЧЕСКИЕ И МЕДИА ФАЙЛЫ
# ============================================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================
# ПОЛЕ ПЕРВИЧНОГО КЛЮЧА ПО УМОЛЧАНИЮ
# ============================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
